spring.application.name=backend

# Database configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/personal_os?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:personalos}
spring.datasource.password=${DB_PASSWORD:26Anmol@}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080
